name:                aoc2020-day7
version:             0.1.0.0
github:              "kierdavis/aoc2020"
license:             PublicDomain
author:              "Kier Davis"
maintainer:          "me@kierdavis.com"

dependencies:
- base >= 4.7 && < 5
- graphite >= 0.10 && < 0.11
- parsec >= 3 && < 4

executables:
  aoc2020-day7-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
